import imagePh from "../../assets/home-item-card.webp";

const fakeItems = [
  {
    id: 1,
    title: "Small Title",
    price: 14.5,
    description: "irrelevant for now",
    category: "CA",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 2,
    title: "Item With Medium Title",
    price: 14.5,
    description: "irrelevant for now",
    category: "CA",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 3,
    title: "Item With a Kinda Long Title",
    price: 14.5,
    description: "irrelevant for now",
    category: "CA",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 4,
    title: "CA",
    price: 14.5,
    description: "irrelevant for now",
    category: "CA",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 5,
    title: "Small Title",
    price: 14.5,
    description: "irrelevant for now",
    category: "CB",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 6,
    title: "Item With Medium Title",
    price: 14.5,
    description: "irrelevant for now",
    category: "CB",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 7,
    title: "Item With a Kinda Long Title",
    price: 14.5,
    description: "irrelevant for now",
    category: "CB",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 8,
    title: "CB",
    price: 14.5,
    description: "irrelevant for now",
    category: "CB",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 9,
    title: "Small Title",
    price: 14.5,
    description: "irrelevant for now",
    category: "CC",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 10,
    title: "Item With Medium Title",
    price: 14.5,
    description: "irrelevant for now",
    category: "CC",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 11,
    title: "Item With a Kinda Long Title",
    price: 14.5,
    description: "irrelevant for now",
    category: "CC",
    rating: "4/5",
    img: imagePh,
  },
  {
    id: 12,
    title: "CC",
    price: 14.5,
    description: "irrelevant for now",
    category: "CC",
    rating: "4/5",
    img: imagePh,
  },
];

export default fakeItems;
